### PR TITLE
add checkbox for the net ads join --no-dns-updates switch

### PR DESCRIPTION
**Pull request by aaptel**
SLE12SP2 net ads join utility has a new --no-dns-updates option (bsc#991564) this change adds a checkbox in the AD join popup and the autoyast UI to reflect that.

### CODE REVIEW

**Comment by aaptel** [comment]
Actually, it's not done yet sorry. I'll update the PR when I'm done.

**Comment by aaptel** [comment]
Should be ok now.

**Comment by jreidinger** [comment]
looks good, please update it to resolve conflict and bump version. Thanks

**Comment by teclator** [comment]
@ddiss @aaptel what about this one, the requested changes are also waiting for one year at least.

**Comment by teclator** [comment]
@aaptel I will close it by now, it needs some adaptations for being able to merge. Please, feel free to reopen it if you plan to adapt or just create a new one.

**Pull request closed without merging**
