### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by noelpower**

### CODE REVIEW

**Review by dmulder — CHANGES_REQUESTED** [review]
@noelpower could you please rebase this patch series, and remove the 'adapt rakefile/dockerfile' patches which get added, then reverted? I'd rather we didn't push those into the commit history.

**Comment by noelpower** [comment]
hmm, I thought I followed the maint procedure correctly see [here](https://yastgithubio.readthedocs.io/en/latest/maintenance-branches/#branch-specific-commits)

**Comment by noelpower** [comment]
Have to admit I am not sure about version number bumping and rules for that

**Comment by dmulder** [comment]
> hmm, I thought I followed the maint procedure correctly see [here](https://yastgithubio.readthedocs.io/en/latest/maintenance-branches/#branch-specific-commits)

oh, yuck. You are right. That's really bad practice, but if the rules here say to do that... who am I to judge?

**Comment by dmulder** [comment]
> Have to admit I am not sure about version number bumping and rules for that

The only rule I'm aware of is it must increment, or the change doesn't get submitted to obs ;)

**Review by dmulder — APPROVED** [review]
LGTM

**Pull request merged**
